### ISSUE TITLE
PS #6 Q1 Part (b)

### ISSUE THREAD

**Issue by keertanavc** [UC-MACSS/persp-model-econ_W19#10]
In the PS for plotting the data, we've been asked to use this this package:
```
from pandas.plotting import scatter_matrix 
scatter_matrix(df_quant, alpha=0.3, figsize=(6, 6), diagonal='kde')

```
But the plot quality isn't that great. The seaborn package does a much better job at producing the same plot:
```
import seaborn as sns
sns.pairplot(auto_df, dropna=True)
```

Can I go ahead with the seaborn version? Ty!

**Comment by rickecon** [comment]
@keertanavc Of course.
