### ISSUE TITLE
PS #6 Q1 Part (f)

### ISSUE THREAD

**Issue by keertanavc** [UC-MACSS/persp-model-econ_W19#11]
In this part, we've been asked to predict the mpg values from the model that was built. The given model year for prediction is 1999.  In the auto data that's been given, the variable 'year' takes values between 70 and 82.  So shouldn't we be using 99 and not 1999 for  prediction?

**Comment by liu431** [comment]
Although this is strange, I asked Dr. Evans about this on Monday and he said yes.

**Comment by rickecon** [comment]
@keertanavc Yes. Just use the two-digit "99" as the data representation of "1999".
