### ISSUE TITLE
Typo in Confusion Matrix

### ISSUE THREAD

**Issue by liu431** [UC-MACSS/persp-model-econ_W19#14]
In the notebook LogitKNN, we have the following for confusion matrix:
[[180,  32],
  [ 48,  96]]),
where 180 is True Positives, 32 is False Positives, 48 is False Negatives, and 96 is True Negatives.

So the matrix is telling us that 180 and 96 are the numbers of correct predictions.
The model predicts 32 passengers who actually died as survived and 48 passengers who actually survived as died.

**Comment by rickecon** [comment]
Thank you @liu431 . I was confused.
