### ISSUE TITLE
LSQUnivariateSpline requires strictly increasing x

### ISSUE THREAD

**Issue by liu431** [UC-MACSS/persp-model-econ_W19#15]
In the PS7 Q2, you might encounter this error for creating the linear/cublic spline object:

`ValueError: x must be strictly increasing
`
The LSQUnivariateSpline enforces input array to be strictly increasing since 2017 (Github [Issue](https://github.com/scipy/scipy/issues/6959)). Here are three ways I have thought of to get around:

1. Use the older Scipy version before the check is implemented. It seems this is what some last years' students did (Github [issue](https://github.com/UC-MACSS/persp-model_W18/issues/192)). I didn't think this is an efficient approach.

2. Implement the spline function from scratch. I did the linear spline and am working on cubic spline. However, the question requires to use LQUnivariateSpline.

3. Grouping the data by the age with average Coolness
`df2=df.groupby('Age').mean()`
`df2['Age']=df2.index`
The new dataframe will look like this:

Age | Cool
-- | --

11.0 | 10.110237
12.0 | 9.365623
13.0 | 10.015882
14.0 | 11.747109
15.0 | 15.434739

This solves the problem.

Here is the link to my interactive plot:

https://plot.ly/~lliu95877/4/coolness-index-against-age/

**Comment by rickecon** [comment]
@liu431 No. This works fine on my computer, without any errors. Here is some code.

```python
import scipy.interpolate as si

knots = [22, 40, 59, 77]
# Let age and cool_ind be numpy arrays of the data
spl_cub_cool = si.LSQUnivariateSpline(age, cool_ind, knots, k=3)
```
Then you can just plug in a vector of ages into your interpolate object `spl_cub_cool` that will output the interpolated values. If you make an `np.linspace()` vector of a lot of ages between the minimum and maximum of `ages`, you should be able to plot that and get the graph I showed you in class.

**Comment by liu431** [comment]
Got it. Thank you!
