### ISSUE TITLE
(Possible) Minor typo in PS 8

### ISSUE THREAD

**Issue by keertanavc** [UC-MACSS/persp-model-econ_W19#19]
Hi,

I think this is a typo, but I thought I would confirm anyway. So in Q2, you have:

> Create a binary variable mpg high that equals 1 if mpg high≥ median(mpg high) and equals either 0 if mpg high< median(mpg high).

Shouldn't we have median(mpg) instead of median(mpg_high)? Thanks!

**Comment by rickecon** [comment]
@keertanavc . Thanks for finding that. I have updated it now for future generations.
