### ISSUE TITLE
Possible minor typos in PS9

### ISSUE THREAD

**Issue by liu431** [UC-MACSS/persp-model-econ_W19#21]
@rickecon 
Hi Rick,

In (b) logistic regression, we should tune the parameters `penalty` and `C` instead of `max depth`, `min samples split`, and `min samples leaf`.

In (c) random forest, `n_estimators` are the number of trees in the forest. I think it makes more sense to use 
 sp_randint(10,200) instead of [10,200]. If using [10,200], we are only alternating between two values. However, this will add much more computing complexity and not guaranteed to get the best score because of the randomness.

In (d) SVC, shrinking need to be a boolean value, so it could be either [True, False] or [1,0] (this is corrected in class).

**Comment by rickecon** [comment]
@liu431 

Yes, in part (b), I accidentally left that line in from some text I copied from another part.

Yes, in part (c), `n_estimators` should be a `sp_randint`. I also reset `max_depth` to be a `sp_randit.

Yes. fixed the boolean in part (d).
