### ISSUE TITLE
 Composite Simpson’s Rule

### ISSUE THREAD

**Issue by liu431** [UC-MACSS/persp-model-econ_W19#3]
Here is a detailed discussion with Dr. Evans @rickecon about playing around different expressions of the composite Simpson's Rule.

1. 

In the ACME Numerical Integration Notebook, the equation is:

![image](https://user-images.githubusercontent.com/29471085/51190778-95e69600-18a8-11e9-8242-4dae5225ecad.png)

2.

In the Jupyter Notebook, the equation is:

![image](https://user-images.githubusercontent.com/29471085/51190931-f1b11f00-18a8-11e9-90cb-acfa182e92ed.png)

3. In the Numerical Analysis textbook (Burden and Faires, 9th ed), the equation is:

![image](https://user-images.githubusercontent.com/29471085/51191038-291fcb80-18a9-11e9-941f-5800e25c2100.png)

There are several differences: 

a. Denominators are `3(N+1)`,`6N`,`3n` respectively.

b. To have even intervals, 1 and 2 uses `2N` and 3 uses `n`. So it is inconsistent in 1 and 2 to have `N intervals` and nodes `x_0,x_1,...x_2N`. It should be `2N` intervals in 1 and 2.

c. Minor things: 1 and 2 uses `g(x)` and 3 uses `f(x)`. 3 also has an error term which could be ignored for now.

Example:

Suppose we use four intervals (n=2N=4) to approximate the integral,

In 1 and 2, 2N=4, N=2, so the term in squared bracket is `f(x_0)+2*f(x_2)+4*(f(x_1)+f(x_3))+f(x_4)`

In 3, n=4, the term in squared bracket is `g(x_0)+2*g(x_2)+4*(g(x_1)+g(x_3))+g(x_4)`

So they are the same!

My code implementation using Equ 2 (with 2N):
```
N=1000000
a,b=-10,10
g=lambda x: 0.1*x**4-1.5*x**3+0.53*x**2+2*x+1
intersim=[a+i*(b-a)/(2*N) for i in range(2*N+1)]
appsim=(g(intersim[0])+g(intersim[-1])+\
            4*sum(g(i) for i in intersim[1:-1:2])+\
             2*sum(g(i) for i in intersim[2:-2:2]))*(b-a)/(6*N) 
appsim
```
The result will be 4373.333333333138

Conclusion: Follow the equation in the Jupyter notebook will yield correct answer. It's the typo `N intervals` which confuses me in class. Changing it to `2N` will agree with the textbook formula. Hope this helps.

Reference:

Numerical Analysis, 9th edition, by R. Burden and J. Faires

Numerical Integration by ACME at BYU

Numerical Integration notebook by Dr. Evans

**Comment by rickecon** [comment]
Thanks, @liu431 . This is fixed in an updated notebook.
