### ISSUE TITLE
Potential typo on PS3

### ISSUE THREAD

**Issue by jsgenan** [UC-MACSS/persp-model-econ_W19#5]
In exercise 5.16, the question says that the epsilon's mean equals mu, but the distribution is N(0, sigma).  I don't know if somebody has the same question, but I think the center of the distribution should also be mu? Hopefully the issue is not too late.

**Comment by rickecon** [comment]
@jsgenan Yes that is a typo in exercise 5.16. It should read `e~N(mu, sigma2)`.
