### ISSUE TITLE
PS #4, question 1, section a

### ISSUE THREAD

**Issue by keertanavc** [UC-MACSS/persp-model-econ_W19#6]
In that question, we've been asked to set 'normed = True' option. But when I checked about the function online [here](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hist.html), it is given that "normed : bool, optional. Deprecated; use the density keyword argument instead."  Also, in MLE notebook density option is being used. So do we still go ahead and use normed?

**Comment by keertanavc** [comment]
SoI tried using both and they give the same histogram plots. But you'll get a warning if you use 'normed', so I'm guessing that using density is the safer practice.

**Comment by rickecon** [comment]
Use the one that doesn't give the warning. @keertanavc
